### ISSUE TITLE
Bad API request, use POST request, not GET

### ISSUE THREAD

**Issue by donno2048** [gil9red/pastebin3#1]
when I try to:
```python
api_user_key = pastebin3.api_user_key(dev_key, user_name, user_password)
```
I get:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Elisha\Desktop\pastebin3.py", line 83, in api_user_key
    rs = __send_post_request_by_pastebin(__API_LOGIN_URL, params)
  File "C:\Users\Elisha\Desktop\pastebin3.py", line 59, in __send_post_request_by_pastebin
    raise PastebinRequestError(rs)
pastebin3.PastebinRequestError: Bad API request, use POST request, not GET
```

**Comment by gil9red** [comment]
Fixed: 9124ee9686ecc410c6ae921ef2842568ac197fd8 :)
